// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBTxAlrmqIeT1_NmdjMQb9KVR63Pg0hIQ',
    appId: '1:555995865386:web:6648ef5688bd231ea3be53',
    messagingSenderId: '555995865386',
    projectId: 'homehunt-c25da',
    authDomain: 'homehunt-c25da.firebaseapp.com',
    storageBucket: 'homehunt-c25da.firebasestorage.app',
    measurementId: 'G-D0NFD9WYNY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJmZm29OmCTqUwEcoCbtFl6NW_EobxXWQ',
    appId: '1:555995865386:android:7f32b9f41a7367fba3be53',
    messagingSenderId: '555995865386',
    projectId: 'homehunt-c25da',
    storageBucket: 'homehunt-c25da.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7HimljLF5Vn49TXsC6WeNFcSl_oZPGi4',
    appId: '1:555995865386:ios:030edcca4b8dae20a3be53',
    messagingSenderId: '555995865386',
    projectId: 'homehunt-c25da',
    storageBucket: 'homehunt-c25da.firebasestorage.app',
    iosBundleId: 'com.example.homehunt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7HimljLF5Vn49TXsC6WeNFcSl_oZPGi4',
    appId: '1:555995865386:ios:030edcca4b8dae20a3be53',
    messagingSenderId: '555995865386',
    projectId: 'homehunt-c25da',
    storageBucket: 'homehunt-c25da.firebasestorage.app',
    iosBundleId: 'com.example.homehunt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBTxAlrmqIeT1_NmdjMQb9KVR63Pg0hIQ',
    appId: '1:555995865386:web:29e94fd36601e936a3be53',
    messagingSenderId: '555995865386',
    projectId: 'homehunt-c25da',
    authDomain: 'homehunt-c25da.firebaseapp.com',
    storageBucket: 'homehunt-c25da.firebasestorage.app',
    measurementId: 'G-PS6EYSKFF6',
  );
}
